// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/resource/analyze": {
    params: {};
  };
  "/privacy": {
    params: {};
  };
  "/terms": {
    params: {};
  };
  "/robots.txt": {
    params: {};
  };
  "/.well-known/appspecific/com.chrome.devtools.json": {
    params: {};
  };
  "/action/set-theme": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/resource/analyze" | "/privacy" | "/terms" | "/robots.txt" | "/.well-known/appspecific/com.chrome.devtools.json" | "/action/set-theme" | "/*";
  };
  "routes/home/route.tsx": {
    id: "routes/home/route";
    page: "/";
  };
  "routes/api/analyze/route.ts": {
    id: "routes/api/analyze/route";
    page: "/resource/analyze";
  };
  "routes/privacy/route.tsx": {
    id: "routes/privacy/route";
    page: "/privacy";
  };
  "routes/terms/route.tsx": {
    id: "routes/terms/route";
    page: "/terms";
  };
  "routes/robots.txt.ts": {
    id: "routes/robots.txt";
    page: "/robots.txt";
  };
  "routes/well-known-devtools.ts": {
    id: "routes/well-known-devtools";
    page: "/.well-known/appspecific/com.chrome.devtools.json";
  };
  "routes/action.set-theme.ts": {
    id: "routes/action.set-theme";
    page: "/action/set-theme";
  };
  "routes/not-found.tsx": {
    id: "routes/not-found";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home/route": typeof import("./app/routes/home/route.tsx");
  "routes/api/analyze/route": typeof import("./app/routes/api/analyze/route.ts");
  "routes/privacy/route": typeof import("./app/routes/privacy/route.tsx");
  "routes/terms/route": typeof import("./app/routes/terms/route.tsx");
  "routes/robots.txt": typeof import("./app/routes/robots.txt.ts");
  "routes/well-known-devtools": typeof import("./app/routes/well-known-devtools.ts");
  "routes/action.set-theme": typeof import("./app/routes/action.set-theme.ts");
  "routes/not-found": typeof import("./app/routes/not-found.tsx");
};