export type ErrorClass =
  | 'CPU_LIMIT_EXCEEDED'
  | 'ROUTE_NOT_FOUND'
  | 'THEME_CONTEXT_MISSING'
  | 'UNEXPECTED_NATIVE_FORM_SUBMIT'
  | 'ANALYZE_AUTH_FAILED'
  | 'ANALYZE_RATE_LIMITED'
  | 'ANALYZE_VALIDATION_FAILED'
  | 'ANALYZE_INTERNAL_ERROR';
